"""migr from SQLite to Postgres 

Revision ID: 6e19fbdc0ab9
Revises: cd2bcd68998d
Create Date: 2023-03-04 23:39:55.159441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e19fbdc0ab9'
down_revision = 'cd2bcd68998d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
